word_1=input("noun; a year; ")
word_2=input("noun; plural; ")
word_3=input("verb; any; ")
word_4=input("noun; name of a company; ")
word_5=input('verb; end in "ing"; ')
word_6=input("noun; any; ")
word_7=input('verb; end in "ed"; ')
word_8=input("adjective; any; ")
word_9=input("noun; liquid; ")
word_10=input("number; any; ")
word_11=input("noun; any; ")
word_12=input("adjective; any; ")
word_13=input('verb; ending in "ed"; ')
word_14=input("noun; any; ")
word_15=input("plural; type of measurement; ")
word_16=input("noun; type of building; ")
word_17=input("noun; any; ")

print("It was the end of the {} year, and summer was upon us.".format(word_1)) 
print("We gathered together for the roadtrip of our {}. Our Destination,".format(word_2))
print("you {}? {} World, of course, with a nice stop at the beach for".format(word_3, word_4))
print("some {} and {} bathing. Of course, as it always is, things didn`t".format(word_5, word_6))
print("go exactly as {}. One car got a {} tire, and another ran out of {}.".format(word_7, word_8, word_9))
print("We didn`t even get there until {} day(s) after we had planned to.".format(word_10))
print("But it didn`t matter. We were determined to have {}. So we went to".format(word_11))
print("the {} theme park... and it {}. We went to the beach, and it was".format(word_12, word_13))
print("closed due to the {}. So what did we do for our vacation? We drove".format(word_14))
print("over 1000 {} to stay in a {} and watch a bunch of {}.".format(word_15, word_16, word_17))